version: "3.8"

services:
  backend:
    build: ./backend
    container_name: task3-backend
    volumes:
      - ./backend/db:/db
    ports:
      - "5000:5000"
    networks:
      - app_net

  frontend:
    build: ./frontend
    container_name: task3-frontend
    ports:
      - "8081:80"
    environment:
      - API_URL=http://backend:5000
    depends_on:
      - backend
    networks:
      - app_net

networks:
  app_net:
    driver: bridge
